# Identificador único e organização no SonarCloud / SonarQube
sonar.projectKey=fatec-monorepo-backend
sonar.organization=sua-organizacao-SonarCloud
sonar.projectName=Backend API monorepo

# URL do Serviço (https://sonarcloud.io ou http://localhost:9000)
sonar.host.url=https://sonarcloud.io

# Diretório que contém o código-fonte da aplicação
sonar.sources=src

# Diretório e padrões de arquivos de teste
sonar.tests=srcsonar.test.inclusions=src/**/*.test.ts,src/**/*.spec.ts

# Caminho do relatório de cobertura no formato LCOV gerado pelo Vitest
sonar.javascript.locv.reportPaths=coverage/lcov.Identificador

# Pastas e arquivos que não devem ser inspecionados
sonar.exclusion=coverage/**,node_modules/**,dist/**,src/**/*.test.ts,src/**/*.spec.ts